version: "3.8"

services:
  # Produit Service
  produit-service:
    build:
      context: ./produit-service
    environment:
      - PGHOST=pgpool
      - PGPORT=5433 # Se connecter à PgPool sur le port exposé
      - PGUSER=postgres
      - PGPASSWORD=mot_de_passe_postgres
      - PGDATABASE=produits_db
      - PORT=4000
    ports:
      - "4000:4000"
    networks:
      - pgnet
    depends_on:
      - pgpool

  # Commande Service
  commande-service:
    build:
      context: ./commande-service
    environment:
      - PGHOST=pgpool
      - PGPORT=5433 # Se connecter à PgPool sur le port exposé
      - PGUSER=postgres
      - PGPASSWORD=mot_de_passe_postgres
      - PGDATABASE=commandes_db
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - pgnet
    depends_on:
      - pgpool

  # API Gateway
  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    environment:
      - GATEWAY_PORT=3000
    depends_on:
      - produit-service
      - commande-service
    networks:
      - pgnet

  # PostgreSQL Master (Primary)
  primary:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replication_user
      - POSTGRESQL_REPLICATION_PASSWORD=replication_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=mot_de_passe_postgres
      - POSTGRESQL_DATABASE=produits_db
    volumes:
      - primary_data:/bitnami/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - pgnet

  # PostgreSQL Replica (Slave)
  replica:
    image: bitnami/postgresql:latest
    depends_on:
      - primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replication_user
      - POSTGRESQL_REPLICATION_PASSWORD=replication_password
      - POSTGRESQL_MASTER_HOST=primary
      - POSTGRESQL_PASSWORD=mot_de_passe_postgres
    volumes:
      - replica_data:/bitnami/postgresql
    ports:
      - "5434:5432"
    networks:
      - pgnet

  # PgPool (Load Balancer for PostgreSQL)
  pgpool:
    image: bitnami/pgpool:latest
    depends_on:
      - primary
      - replica
    environment:
      - PGPOOL_BACKEND_NODES=0:primary:5432,1:replica:5432
      - PGPOOL_SR_CHECK_USER=replication_user
      - PGPOOL_SR_CHECK_PASSWORD=replication_password
      - PGPOOL_HEALTH_CHECK_USER=postgres
      - PGPOOL_HEALTH_CHECK_PASSWORD=mot_de_passe_postgres
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=mot_de_passe_postgres
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpass
    ports:
      - "5433:5432" # Port exposé pour PgPool
    networks:
      - pgnet

volumes:
  primary_data:
  replica_data:

networks:
  pgnet:
    driver: bridge
